<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Query as Query;

/**
 * MoviesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoviesRepository extends \Doctrine\ORM\EntityRepository
{
    public function listWithOrder($order = "asc") {

        $qb = $this
            ->createQueryBuilder("m")
            ->orderBy("m.name", $order)
            ->getQuery()
        ;

        return $qb->getResult();
    }
}
